import type { ClubOption } from '../types';

export const POPULAR_CLUBS: ClubOption[] = [
  {
    clubId: 'real_madrid',
    clubName: 'Real Madrid',
    clubCnName: '皇家马德里',
    wikidataQid: 'Q8682',
    country: 'Spain',
    displayOrder: 1,
  },
  {
    clubId: 'barcelona',
    clubName: 'Barcelona',
    clubCnName: '巴塞罗那',
    wikidataQid: 'Q7156',
    country: 'Spain',
    displayOrder: 2,
  },
  {
    clubId: 'manchester_united',
    clubName: 'Manchester United',
    clubCnName: '曼联',
    wikidataQid: 'Q18656',
    country: 'England',
    displayOrder: 3,
  },
  {
    clubId: 'liverpool',
    clubName: 'Liverpool',
    clubCnName: '利物浦',
    wikidataQid: 'Q1130849',
    country: 'England',
    displayOrder: 4,
  },
  {
    clubId: 'arsenal',
    clubName: 'Arsenal',
    clubCnName: '阿森纳',
    wikidataQid: 'Q9617',
    country: 'England',
    displayOrder: 5,
  },
  {
    clubId: 'chelsea',
    clubName: 'Chelsea',
    clubCnName: '切尔西',
    wikidataQid: 'Q9616',
    country: 'England',
    displayOrder: 6,
  },
  {
    clubId: 'manchester_city',
    clubName: 'Manchester City',
    clubCnName: '曼城',
    wikidataQid: 'Q50602',
    country: 'England',
    displayOrder: 7,
  },
  {
    clubId: 'bayern_munich',
    clubName: 'Bayern Munich',
    clubCnName: '拜仁慕尼黑',
    wikidataQid: 'Q15789',
    country: 'Germany',
    displayOrder: 8,
  },
  {
    clubId: 'juventus',
    clubName: 'Juventus',
    clubCnName: '尤文图斯',
    wikidataQid: 'Q1422',
    country: 'Italy',
    displayOrder: 9,
  },
  {
    clubId: 'ac_milan',
    clubName: 'AC Milan',
    clubCnName: 'AC米兰',
    wikidataQid: 'Q1543',
    country: 'Italy',
    displayOrder: 10,
  },
  {
    clubId: 'inter_milan',
    clubName: 'Inter Milan',
    clubCnName: '国际米兰',
    wikidataQid: 'Q631',
    country: 'Italy',
    displayOrder: 11,
  },
  {
    clubId: 'paris_saint_germain',
    clubName: 'Paris Saint-Germain',
    clubCnName: '巴黎圣日耳曼',
    wikidataQid: 'Q483020',
    country: 'France',
    displayOrder: 12,
  },
  {
    clubId: 'ajax',
    clubName: 'Ajax',
    clubCnName: '阿贾克斯',
    wikidataQid: 'Q81888',
    country: 'Netherlands',
    displayOrder: 13,
  },
  {
    clubId: 'borussia_dortmund',
    clubName: 'Borussia Dortmund',
    clubCnName: '多特蒙德',
    wikidataQid: 'Q41420',
    country: 'Germany',
    displayOrder: 14,
  },
  {
    clubId: 'tottenham_hotspur',
    clubName: 'Tottenham Hotspur',
    clubCnName: '托特纳姆热刺',
    wikidataQid: 'Q18741',
    country: 'England',
    displayOrder: 15,
  },
  {
    clubId: 'atletico_madrid',
    clubName: 'Atletico Madrid',
    clubCnName: '马德里竞技',
    wikidataQid: 'Q8701',
    country: 'Spain',
    displayOrder: 16,
  },
  {
    clubId: 'inter_miami',
    clubName: 'Inter Miami CF',
    clubCnName: '迈阿密国际',
    wikidataQid: 'Q16844931',
    country: 'United States',
    displayOrder: 17,
  },
  {
    clubId: 'benfica',
    clubName: 'Benfica',
    clubCnName: '本菲卡',
    wikidataQid: 'Q131499',
    country: 'Portugal',
    displayOrder: 18,
  },
  {
    clubId: 'porto',
    clubName: 'Porto',
    clubCnName: '波尔图',
    wikidataQid: 'Q128446',
    country: 'Portugal',
    displayOrder: 19,
  },
  {
    clubId: 'celtic',
    clubName: 'Celtic',
    clubCnName: '凯尔特人',
    wikidataQid: 'Q19593',
    country: 'Scotland',
    displayOrder: 20,
  },
  {
    clubId: 'rangers',
    clubName: 'Rangers',
    clubCnName: '格拉斯哥流浪者',
    wikidataQid: 'Q19597',
    country: 'Scotland',
    displayOrder: 21,
  },
  {
    clubId: 'napoli',
    clubName: 'Napoli',
    clubCnName: '那不勒斯',
    wikidataQid: 'Q2641',
    country: 'Italy',
    displayOrder: 22,
  },
  {
    clubId: 'roma',
    clubName: 'Roma',
    clubCnName: '罗马',
    wikidataQid: 'Q2739',
    country: 'Italy',
    displayOrder: 23,
  },
  {
    clubId: 'lazio',
    clubName: 'Lazio',
    clubCnName: '拉齐奥',
    wikidataQid: 'Q2609',
    country: 'Italy',
    displayOrder: 24,
  },
  {
    clubId: 'valencia',
    clubName: 'Valencia',
    clubCnName: '瓦伦西亚',
    wikidataQid: 'Q10333',
    country: 'Spain',
    displayOrder: 25,
  },
  {
    clubId: 'sevilla',
    clubName: 'Sevilla',
    clubCnName: '塞维利亚',
    wikidataQid: 'Q10329',
    country: 'Spain',
    displayOrder: 26,
  },
  {
    clubId: 'santos',
    clubName: 'Santos',
    clubCnName: '桑托斯',
    wikidataQid: 'Q80955',
    country: 'Brazil',
    displayOrder: 27,
  },
  {
    clubId: 'boca_juniors',
    clubName: 'Boca Juniors',
    clubCnName: '博卡青年',
    wikidataQid: 'Q170703',
    country: 'Argentina',
    displayOrder: 28,
  },
  {
    clubId: 'river_plate',
    clubName: 'River Plate',
    clubCnName: '河床',
    wikidataQid: 'Q15799',
    country: 'Argentina',
    displayOrder: 29,
  },
  {
    clubId: 'flamengo',
    clubName: 'Flamengo',
    clubCnName: '弗拉门戈',
    wikidataQid: 'Q17479',
    country: 'Brazil',
    displayOrder: 30,
  },
];
